issue_reporter_src/urls.py
from django.contrib import admin
from django.urls import path,include
from infolist.views import meet_links_webpage

urlpatterns = [
    path('admin/', admin.site.urls),
    #External
    path('accounts/', include('allauth.urls')),
    path('tinymce/', include('tinymce.urls')),
    #Local
    path('',include('reporter.urls',namespace='reporter')),
    path('polling/',include('polling.urls',namespace='polling')),
    path('info-list/',include('infolist.urls',namespace='infolist')),
    path("msm19/",meet_links_webpage),
]

polling/urls.py
from django.urls import path
from . import views

app_name = 'polling'

urlpatterns=[
    path('',views.polling_list_view,name='list'),
    path('<int:id>/',views.polling_detail_view,name='detail'),
    path('submit/',views.poll_submit_view,name='submit'),
    path('close/<int:id>/',views.poll_close_view,name='close'),
    path('delete/<int:id>/',views.poll_delete_view,name='delete'),
    path('results/',views.poll_results_list,name='result-list'),
    path('result/<int:id>/',views.poll_result_detail,name='result-detail'),

    #API ENDPOINTS
    path('new/',views.poll_create_view,name='create'),
]

reporter/urls.py
from django.urls import path
from . import views

app_name = 'reporter'

urlpatterns=[
    path('',views.index_view,name='index'),
    path('about-us/',views.about_view,name='about'),
    path('feed-back/',views.feedback_view,name='feed-back'),
    path('documentation/',views.documentation_view,name='documentation'),
    path('send-mail/',views.send_remainder_mail_view,name='mail'),

    path('report/',views.issue_form_view,name='issue-form'),
    path('close-stage/<int:pk>/',views.close_issue_view,name='close-issue'),
    path('close-delete/<int:pk>/',views.delete_resolve_line_view,name='resolve-line-delete'),
    path('resolved/',views.resolved_view,name='resolved'),
    path('resolve-issue/<int:pk>',views.resolve_issue_view,name='resolve-issue'),
    path('close/',views.close_view,name='close-stage'),
    path('delete/<int:pk>/',views.delete_issue_view,name='delete'),
    path('edit/<int:pk>/',views.edit_issue_view,name='edit'),
    path('voted-list/',views.voted_list_view,name='voted-list'),
    path('deadline-add/',views.deadline_add_view,name='add-deadline'),
    path('deadline-remove/<int:pk>',views.deadline_remove_view,name='remove-deadline'),
    path('voted-list/<int:id>/',views.voted_users,name='voted-users'),
    
    path('contact-list/',views.contactlist_list_view,name='contact-list'),
    path('contact-pending/',views.contactlist_cr_pending_list,name='contact-pending'),
    path('contact-add/',views.contactlist_add_view,name='contact-add'),
    path('contact-approve/<int:pk>/',views.contactlist_approve_view,name='contact-approve'),
    path('contact-delete/<int:pk>/',views.contactlist_delete_view,name='contact-delete'),

    #Vote API EndPoints
    path('update-vote/',views.vote_update_view,name='vote-update'),
    path('get-vote/',views.vote_get_view,name='vote-get'),
]

polling/models.py
from django.db import models

from profiles.models import UserInfo

class Option(models.Model):
    text = models.CharField(max_length=128)

    def __str__(self):
        return str(self.text[:20])

class Poll(models.Model):
    user = models.ForeignKey(UserInfo,on_delete=models.CASCADE,related_name='polluser',blank=True)
    statement = models.CharField(max_length=128)
    options = models.ManyToManyField(Option,blank=True,related_name='poll')
    department = models.CharField(max_length=20,blank=True)
    join = models.CharField(max_length=4,blank=True)
    active = models.BooleanField(default=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.statement[:20]} by {self.user}"
    

class OptionCount(models.Model):
    option = models.ForeignKey(Option,on_delete=models.CASCADE,related_name='count')
    count = models.PositiveIntegerField(default=0)

    def __str__(self):
        return f'Count of {self.option}'



class PollResult(models.Model):
    poll = models.ForeignKey(Poll,on_delete=models.CASCADE,related_name='result')
    option_count = models.ManyToManyField(OptionCount)
    voted_users = models.ManyToManyField('UserPoll')

    def __str__(self):
        return f'Result of {self.poll}'

    
class UserPoll(models.Model):
    user = models.ForeignKey(UserInfo,on_delete=models.CASCADE)
    poll = models.ForeignKey(PollResult,on_delete=models.CASCADE)
    option = models.ForeignKey(OptionCount,on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user} selected {self.option.option}'

polling/forms.py
from django import forms

from .models import Poll

class PollForm(forms.ModelForm):
    class Meta:
        model = Poll
        exclude = ['join','department','user','active','options']

polling/views.py
from django.shortcuts import render,redirect ,get_object_or_404
from django.core.exceptions import PermissionDenied
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import JsonResponse
import json

from .models import Poll,Option,PollResult,OptionCount,UserPoll
from .forms import PollForm

@login_required
def polling_list_view(request):
    qs = Poll.objects.filter(active=True,department=request.user.info.department,join=request.user.info.join_year).order_by('-timestamp')
    return render(request,'polling/poll-list.html',{'object_list':qs})


@login_required
def polling_detail_view(request,id):
    object = get_object_or_404(Poll,pk=id)
    if(not object.active):
        raise PermissionDenied
    options = object.options.all()
    options_ =  []
    for i in options:
        options_.append(i)
    options_.reverse()
    live_votes = object.result.all().first()
    if(not live_votes is None):
        live_votes = live_votes.voted_users.all().count()
    else:
        live_votes = 0
    return render(request,'polling/poll-detail.html',{"object":object,'options':options_,'live_voted':live_votes})


@login_required
def poll_create_view(request):
    if(not request.user.info.is_cr):
        raise PermissionDenied
    form = PollForm()
    if(request.method=='POST'):
        data = json.loads(request.body)
        obj = Poll.objects.create(  
            user = request.user.info,
            statement = data['statement'],
            department= request.user.info.department,
            join = request.user.info.join_year
        )
        options = data['option']
        for i in options:
            new_option = Option.objects.create(text=i)
            obj.options.add(new_option)
        obj.save()
        messages.success(request, 'Poll is Created')
        return JsonResponse({"Success":"Created"},status=200)
    return render(request,'polling/poll-create.html',{"form":form})


@login_required
def poll_submit_view(request):
    if(request.method=='POST'):
        poll_id = request.POST.get('poll',None)
        option_id = request.POST.get('option',None)
        poll_obj = get_object_or_404(Poll,pk=poll_id)
        option_obj = get_object_or_404(Option,pk=option_id)
        user = request.user.info

        option_count,created = OptionCount.objects.get_or_create(option=option_obj)
        poll_result,created0 = PollResult.objects.get_or_create(poll=poll_obj)

        available_options = poll_result.option_count
        if(not option_count in available_options.all()):
            available_options.add(option_count)
            poll_result.save()

        voted_users = poll_result.voted_users.all()
        voted_users_obj = []
        for i in voted_users:
            voted_users_obj.append(i.user)
        if(user in voted_users_obj):
            already_voted_user = UserPoll.objects.get(user=user,poll=poll_result)   
            voted_option = already_voted_user.option
            if(voted_option==option_count):
                messages.success(request,"Your Option has Been Submitted!")
                return redirect("polling:list")
            voted_option.count-=1
            voted_option.save()
            already_voted_user.option = option_count
            already_voted_user.save()
        else:
            new_vote_user = UserPoll.objects.create(user=user,poll=poll_result,option=option_count)
            poll_result.voted_users.add(new_vote_user)
            poll_result.save()
        option_count.count+=1
        option_count.save()
        messages.success(request,"Your Option has Been Submitted!")
        return redirect("polling:list")
    raise PermissionDenied


@login_required
def poll_close_view(request,id):
    if(not request.user.info.is_cr):
        raise PermissionDenied
    poll_obj = get_object_or_404(Poll,pk=id)
    poll_obj.active = False
    poll_obj.save()
    messages.info(request,"Poll has Been Closed!")
    return redirect("polling:list")


@login_required
def poll_delete_view(request,id):
    if(not request.user.info.is_cr):
        raise PermissionDenied
    poll_obj = get_object_or_404(Poll,pk=id)
    options = poll_obj.options.all()
    for i in options:
        i.delete()
    poll_obj.delete()
    messages.info(request,"Poll has Been Deleted!")
    return redirect("polling:list")


@login_required
def poll_results_list(request):
    qs = Poll.objects.filter(active=False,department=request.user.info.department,join=request.user.info.join_year).order_by('-updated')
    return render(request,'polling/poll-results-list.html',{'object_list':qs})


@login_required
def poll_result_detail(request,id):
    object = get_object_or_404(Poll,pk=id)
    options_obj = object.options.all()
    total_votes = 0
    for i in options_obj:
        try:
            temp = i.count.all().first().count
            total_votes+=temp
        except:
            continue
    options = []
    for i in options_obj:
        temp_list = {}
        opt_percent = 0.0
        opt_number = 0
        try:
            opt_percent = ((i.count.all().first().count)/total_votes)*100
            opt_percent = round(opt_percent,2)
            opt_number = i.count.all().first().count
        except:
            pass
        opt_text = i.text
        temp_list["percent"] = str(opt_percent)
        temp_list["number"] = opt_number
        temp_list["text"] = opt_text
        options.append(temp_list)
    return render(request,'polling/poll-result-detail.html',{'object':object,'options':options})

polling/templates/polling/modal_.html
<!-- Modal -->
<div class="modal fade" id="deletePoll" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Are you Sure Want to Delete?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
          <a class="btn btn-danger" href="{% url 'polling:delete' id %}">Delete</a>
        </div>
      </div>
    </div>
  </div>

polling/templates/polling/poll-create.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<h2 class="mt-2">Create New Poll</h2>
<a href="{% url 'polling:list' %}"><i class="fa fa-arrow-left"></i> Live Polls</a>
<hr>
<div>
    <div class="row">
        <div class="col-lg-7 col-md-10 col-sm-12">
            <form id="poll-form" action="{% url 'polling:create' %}" method="post">
                {% csrf_token %}
                {{form|crispy}}
                <br>
                <input class="btn btn-primary mb-2 mt-2" type="submit" value="Create">
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block script %} <script src="{% static 'js/polling.js' %}"></script> {% endblock %}

polling/templates/polling/poll-detail.html
{% extends 'base.html' %}

{% block content %}
<h2 class="mt-2 text-center">Poll</h2>
<a class="mt-2 inline-block" href="{% url 'polling:list' %}"><i class="fa fa-arrow-left"></i> Live Polls</a>
<p>Your Vote is Anonymized!</p>
<hr>
<div class="row">
    <div class="col-12">
        <h3 class="lead">Statement: {{object.statement}}</h3>
    </div>
    <form action="{% url 'polling:submit' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="poll" value="{{object.id}}">
        {% for option in options %}
        <div class="col-12 form-check ml-3 mb-2">
            <input class="form-check-input" type="radio" id="{{option.id}}" name="option" value="{{option.id}}">
            <label class="form-check-label" for="{{option.id}}">{{option.text}}</label><br>
        </div>
        {% empty %}
        <p class="lead ml-2">No Option Available!</p>
        {% endfor %}
        {% if options %}
        <input class="btn btn-primary ml-2" type="submit" value="Submit">
        <p class="lead mt-2 ml-2">If already Submitted, Re-Submit to Update your Vote!</p>
        {% endif %}
    </form>
</div>
{% if request.user.info.is_cr %}
<a class="btn btn-success mb-3" href="{% url 'polling:close' object.id %}"><i class="fa fa-ban"></i> Close Poll</a>
<button type="button" class="btn btn-danger mb-3" data-toggle="modal" data-target="#deletePoll"><i class="fa fa-trash-o"></i> Delete</button>
<p>Voted Till Now: {{live_voted}}</p>
{% endif %}
{% include 'polling/modal_.html' with id=object.id %}
{% endblock %}

polling/templates/polling/poll-list.html
{% extends 'base.html' %}

{% block content %}

<h2 class="mt-3 text-center">TeamEzI Resolved</h2>
<h4 class="inline-block">Department: {{request.user.info.department|upper}} {{request.user.info.join_year}}</h4>
<a class="btn btn-secondary ml-3 mt-2" href="{% url 'reporter:index' %}"><i class="fa fa-exclamation-circle"></i> Issues</a>
<a href="{% url 'infolist:list' %}" class="btn btn-secondary ml-2 mt-2">Info-List</a>
<h3 class="mt-2">Welcome, {{request.user.first_name}} {{request.user.last_name}}</h3>

{% if request.user.info.is_cr %}
<a class="btn btn-primary btn-sm" href="{% url 'polling:create' %}"><i class="fa fa-plus-square"></i> Create Poll</a>
{% endif %}
<a class="btn btn-success btn-sm" href="{% url 'polling:result-list' %}"><i class="fa fa-file-text-o"></i> Results</a>
<hr>
<h2 class="mt-2 text-center">Live Polls</h2>
<div class="row">
    {% for object in object_list %}
    <div class="col-lg-7 col-md-10 col-sm-12 mb-3">
        <div class="card">
            <div class="card-body">
                {{object.statement}}
            </div>
            <h6 class="card-subtitle mb-2 ml-2 text-muted">{{object.timestamp|date:'d-m-Y H:i'}}</h6>
            <a class="btn btn-primary" href="{% url 'polling:detail' object.id %}"><i class="fa fa-eye"></i> View</a>
        </div>
    </div>
    {% empty %}
    <p class="lead my-2 ml-2">No Live Polls!</p>
    {% endfor %}
</div>

{% endblock %}

polling/templates/polling/poll-result-detail.html
{% extends 'base.html' %}

{% block content %}
<a class="mt-2 inline-block" href="{% url 'polling:list' %}"><i class="fa fa-arrow-left"></i> Live Polls</a>
<hr>
<h3><em>Statement</em>: {{object.statement}}</h3>
<p>Started On {{object.timestamp|date:'d-m-Y H:i'}}</p>
<p>Closed On {{object.updated|date:'d-m-Y H:i'}}</p>
<hr>
{% for option in options %}
    <p>Option {{forloop.counter}}: {{option.text}} (Votes: {{option.number}})</p>
    <div class="row">
        <div class="col-lg-6 col-md-8 col-sm-12 mb-2">
            <div class="progress my-2">
                {% with "width: "|add:option.percent|add:"%" as percent_style %}
            <div class="progress-bar bg-success" role="progressbar" style="{{percent_style}}" aria-valuenow="{{option.percent}}" aria-valuemin="0" aria-valuemax="100">{{option.percent}}%</div>
                {% endwith %}
            </div>
        </div>
    </div>
{% endfor %}
{% if request.user.info.is_cr %}
<button type="button" class="btn btn-danger mb-3" data-toggle="modal" data-target="#deletePoll"><i class="fa fa-trash-o"></i> Delete</button>
{% include 'polling/modal_.html' with id=object.id %}
{% endif %}
{% endblock %}

polling/templates/polling/poll-results-list.html
{% extends 'base.html' %}
{% block content %}
<h2 class="mt-2 text-center">Poll Results</h2>
<a class="mt-2" href="{% url 'polling:list' %}"><i class="fa fa-arrow-left"></i> Live Polls</a>
<hr>
<div class="row">
    {% for object in object_list %}
    <div class="col-lg-7 col-md-10 col-sm-12 mb-3">
        <div class="card">
            <div class="card-body">
                {{object.statement}}
            </div>
            <h6 class="card-subtitle mb-2 ml-2 text-muted">Closed at {{object.updated|date:'d-m-Y H:i'}}</h6>
            <a class="btn btn-primary" href="{% url 'polling:result-detail' object.id %}"><i class="fa fa-eye"></i> View Details</a>
        </div>
    </div>
    {% empty %}
    <p class="lead my-2 ml-2">No Closed Polls Yet!</p>
    {% endfor %}
</div>
{% endblock %}