infolist/urls.py
from django.urls import path
from . import views

app_name = 'infolist'

urlpatterns=[
    path('',views.info_list_display_view,name='list'),
    path('add-subject/',views.info_list_add_subject_view,name='add-subject'),
    path('delete-subject/<int:id>/',views.info_list_delete_subject_view,name='delete-subject'),
    path('add/',views.info_list_add_view,name='add-info'),
    path('pending/',views.info_list_pending_list_view,name='pending'),
    path('approve/<int:id>/',views.info_list_approve_view,name='approve'),
    path('delete/<int:id>/',views.info_list_delete_view,name='delete'),
]

issue_reporter_src/urls.py
from django.contrib import admin
from django.urls import path,include
from infolist.views import meet_links_webpage

urlpatterns = [
    path('admin/', admin.site.urls),
    #External
    path('accounts/', include('allauth.urls')),
    path('tinymce/', include('tinymce.urls')),
    #Local
    path('',include('reporter.urls',namespace='reporter')),
    path('polling/',include('polling.urls',namespace='polling')),
    path('info-list/',include('infolist.urls',namespace='infolist')),
    path("msm19/",meet_links_webpage),
]

polling/urls.py
from django.urls import path
from . import views

app_name = 'polling'

urlpatterns=[
    path('',views.polling_list_view,name='list'),
    path('<int:id>/',views.polling_detail_view,name='detail'),
    path('submit/',views.poll_submit_view,name='submit'),
    path('close/<int:id>/',views.poll_close_view,name='close'),
    path('delete/<int:id>/',views.poll_delete_view,name='delete'),
    path('results/',views.poll_results_list,name='result-list'),
    path('result/<int:id>/',views.poll_result_detail,name='result-detail'),

    #API ENDPOINTS
    path('new/',views.poll_create_view,name='create'),
]

reporter/urls.py
from django.urls import path
from . import views

app_name = 'reporter'

urlpatterns=[
    path('',views.index_view,name='index'),
    path('about-us/',views.about_view,name='about'),
    path('feed-back/',views.feedback_view,name='feed-back'),
    path('documentation/',views.documentation_view,name='documentation'),
    path('send-mail/',views.send_remainder_mail_view,name='mail'),

    path('report/',views.issue_form_view,name='issue-form'),
    path('close-stage/<int:pk>/',views.close_issue_view,name='close-issue'),
    path('close-delete/<int:pk>/',views.delete_resolve_line_view,name='resolve-line-delete'),
    path('resolved/',views.resolved_view,name='resolved'),
    path('resolve-issue/<int:pk>',views.resolve_issue_view,name='resolve-issue'),
    path('close/',views.close_view,name='close-stage'),
    path('delete/<int:pk>/',views.delete_issue_view,name='delete'),
    path('edit/<int:pk>/',views.edit_issue_view,name='edit'),
    path('voted-list/',views.voted_list_view,name='voted-list'),
    path('deadline-add/',views.deadline_add_view,name='add-deadline'),
    path('deadline-remove/<int:pk>',views.deadline_remove_view,name='remove-deadline'),
    path('voted-list/<int:id>/',views.voted_users,name='voted-users'),
    
    path('contact-list/',views.contactlist_list_view,name='contact-list'),
    path('contact-pending/',views.contactlist_cr_pending_list,name='contact-pending'),
    path('contact-add/',views.contactlist_add_view,name='contact-add'),
    path('contact-approve/<int:pk>/',views.contactlist_approve_view,name='contact-approve'),
    path('contact-delete/<int:pk>/',views.contactlist_delete_view,name='contact-delete'),

    #Vote API EndPoints
    path('update-vote/',views.vote_update_view,name='vote-update'),
    path('get-vote/',views.vote_get_view,name='vote-get'),
]

infolist/views.py
from django.shortcuts import redirect, render,get_object_or_404
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.contrib import messages

from .models import InfoList,Subject, MeetLinks
from .forms import InfoListForm,SubjectForm

@login_required
def info_list_display_view(request):
    subjects = Subject.objects.filter(department=request.user.info.department,year=request.user.info.join_year)
    qs = InfoList.objects.filter(department=request.user.info.department,year=request.user.info.join_year,approved=True)
    data = []
    for i in subjects:
        objects = qs.filter(subject=i)
        if(objects.count()==0):
            continue
        data.append([objects,i])
    return render(request,'infolist/list.html',{'object_list':data})

@login_required
def info_list_add_subject_view(request):
    if(not request.user.info.is_cr):
        raise PermissionDenied
    form = SubjectForm()
    subjects = Subject.objects.filter(department=request.user.info.department,year=request.user.info.join_year)
    if request.method=='POST':
        form = SubjectForm(request.POST)
        if(form.is_valid()):
            subject = request.POST.get("subject")
            sub_obj,created = Subject.objects.get_or_create(department=request.user.info.department,year=request.user.info.join_year,subject=subject)
            if created:
                messages.success(request,"Subject Added!")
            else:
                messages.info(request,"Subject Already Exists!")
        else:
            messages.error(request,"Form is Invalid!")
        return redirect('infolist:add-subject')
    return render(request,'infolist/add-subject.html',{'form':form,'subjects':subjects})


@login_required
def info_list_delete_subject_view(request,id):
    object = get_object_or_404(Subject,pk=id)
    object.delete()
    messages.success(request,"Subject has Been Deleted!")
    return redirect("infolist:add-subject")


@login_required
def info_list_add_view(request):
    form = InfoListForm(request.user.info.department,request.user.info.join_year)
    if(request.method=='POST'):
        form = InfoListForm(request.user.info.department,request.user.info.join_year,request.POST)
        if(form.is_valid()):
            instance = form.save(commit=False)
            instance.user = request.user.info
            instance.department = request.user.info.department
            instance.year = request.user.info.join_year
            if(request.user.info.is_cr):
                instance.approved = True
                messages.info(request,"Info has been Added!")
            else:
                messages.info(request,"Info will be Added Once Approved by CR!")
            instance.save()
            return redirect('infolist:list')
    return render(request,'infolist/add-info.html',{'form':form})


@login_required
def info_list_pending_list_view(request):
    subjects = Subject.objects.filter(department=request.user.info.department,year=request.user.info.join_year)
    qs = InfoList.objects.filter(department=request.user.info.department,year=request.user.info.join_year,approved=False)
    data = []
    for i in subjects:
        objects = qs.filter(subject=i)
        if(objects.count()==0):
            continue
        data.append([objects,i])
    return render(request,'infolist/pending-list.html',{'object_list':data})


@login_required
def info_list_approve_view(request,id):
    if(not request.user.info.is_cr):
        raise PermissionDenied
    obj = get_object_or_404(InfoList,pk=id)
    obj.approved = True
    obj.save()
    messages.info(request,"Info has Been Approved!")
    return redirect("infolist:pending")


@login_required
def info_list_delete_view(request,id):
    obj = get_object_or_404(InfoList,pk=id)
    if(request.user.info==obj.user or request.user.info.is_cr):
        obj.delete()
        return redirect("infolist:list")    
    raise PermissionDenied



def meet_links_webpage(request):
    all_links = MeetLinks.objects.all()
    links = {"links": all_links}
    #User Permissions
    return render(request,"infolist/msm19.html", links)

reporter/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseNotAllowed,JsonResponse,HttpResponseServerError
from django.core.exceptions import PermissionDenied
from django.contrib import messages
from django.core.mail import send_mail
from django.conf import settings
import json, datetime, pytz

from .models import Report , Vote, ContactList
from .forms import ReportForm , DeadlineForm, ContactListForm, FeedBackForm
from profiles.models import UserInfo

def index_view(request):
    qs = []
    form = DeadlineForm()
    if request.user.is_authenticated:
        qs = Report.objects.filter(active=True,department=request.user.info.department,year=request.user.info.join_year,resolved=False)
    return render(request,'reporter/index.html',{'issue_list':qs,'form':form})

def about_view(request):
    return render(request,'about.html')

@login_required
def resolved_view(request):
    qs = Report.objects.filter(active=False,department=request.user.info.department,year=request.user.info.join_year,resolved=True).order_by('-updated')
    return render(request,'reporter/resolved.html',{'issue_list':qs})

@login_required
def close_issue_view(request,pk):
    obj = get_object_or_404(Report,id=pk)
    if(request.user.info.is_cr and request.user.info.department == obj.department and request.user.info.join_year == obj.year):
        if(obj.active):
            obj.active = False
        else:
            obj.active = True
        obj.save()
        return redirect('reporter:close-stage')
    raise PermissionDenied


@login_required
def close_view(request):
    if(request.user.info.is_cr):
        if(request.method=='POST'):
            id_ = int(request.POST.get('id',None))
            resolve_message = request.POST.get('c-line',None)
            obj = Report.objects.get(id=id_)
            obj.cr_line = resolve_message
            obj.save()
        qs = Report.objects.filter(active=False,department=request.user.info.department,year=request.user.info.join_year,resolved=False).order_by('-updated')
        return render(request,'reporter/closed.html',{'issue_list':qs})
    raise PermissionDenied


@login_required
def delete_resolve_line_view(request,pk):
    obj = Report.objects.get(id=pk)
    obj.cr_line = None
    obj.save()
    return redirect('reporter:close-stage')


@login_required
def issue_form_view(request):
    form = ReportForm()
    if request.method=='POST':
        form = ReportForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            user_obj = UserInfo.objects.get(user=request.user)
            instance.user = user_obj
            instance.department = request.user.info.department
            instance.year = request.user.info.join_year
            instance.save()
            qs = UserInfo.objects.filter(department=request.user.info.department,join_year=request.user.info.join_year)
            for i in qs:
                (i.total_novotes)+=1
                i.save()
            return redirect('reporter:index')
    return render(request,'reporter/issue-form.html',{'form':form})

@login_required
def resolve_issue_view(request,pk):
    obj = get_object_or_404(Report,id=pk)
    if(request.user.info.is_cr and request.user.info.department == obj.department and request.user.info.join_year == obj.year):
        obj.resolved = True
        obj.save()
        return redirect('reporter:resolved')
    raise PermissionDenied

@login_required
def delete_issue_view(request,pk):
    obj = get_object_or_404(Report,id=pk)
    if((obj.active == True and obj.resolved == False) or (request.user.info.is_cr)):
        if((request.user.info.is_cr and request.user.info.department == obj.department and request.user.info.join_year == obj.year) or (request.user == obj.user.user)):
            obj.delete()
            return redirect('reporter:index')
    raise PermissionDenied

@login_required
def edit_issue_view(request,pk):
    obj = get_object_or_404(Report,id=pk)
    if(obj.active == True and obj.resolved == False):
        form = ReportForm(instance=obj)
        if(request.user==obj.user.user):
            if(request.method=='POST'):
                form = ReportForm(request.POST,instance=obj)
                if(form.is_valid()):
                    form.save()
                return redirect('reporter:index')
            return render(request,'reporter/edit-issue.html',{'form':form,'issue':obj})
    raise PermissionDenied

@login_required
def vote_update_view(request):
    if request.method == 'POST':
        data_ = json.loads(request.body)
        id_ = data_['id']
        type = data_['type']
        try:
            report_obj = Report.objects.get(id=id_)
            vote_obj,created = Vote.objects.get_or_create(user=request.user,issue=report_obj)
            userinfo_obj = UserInfo.objects.get(user=request.user)
        except:
            return HttpResponseServerError()
        if(report_obj.active == True and report_obj.resolved == False):
            if(type=='upvote'):
                (report_obj.upvotes)+=1
                (userinfo_obj.total_upvotes)+=1
                (userinfo_obj.total_novotes)-=1
                vote_obj.type = 1
            elif(type=='downvote'):
                (report_obj.downvotes)-=1
                (userinfo_obj.total_downvotes)-=1
                (userinfo_obj.total_novotes)-=1
                vote_obj.type = 0
            elif(type=='downvoted'):
                (report_obj.downvotes)+=1
                (userinfo_obj.total_downvotes)+=1
                (userinfo_obj.total_novotes)+=1
                vote_obj.type = -1
            elif(type=='upvoted'):
                (report_obj.upvotes)-=1
                (userinfo_obj.total_upvotes)-=1
                (userinfo_obj.total_novotes)+=1
                vote_obj.type = -1
            report_obj.save()
            vote_obj.save()
            userinfo_obj.save()
            return JsonResponse({'Success':'Voted'})
    return HttpResponseNotAllowed('POST')


@login_required
def vote_get_view(request):
    if request.method == 'POST':
        data_ = json.loads(request.body)
        id_ = data_['id']
        report_obj = Report.objects.get(id=id_)
        data = {}
        obj,created = Vote.objects.get_or_create(user=request.user,issue=report_obj)
        type_ = obj.type
        if(type_ == 1):
            data = {'type':'upvoted'}
        elif(type_ == 0):
            data = {'type':'downvoted'}
        elif(type_ == -1):
            data = {'type':'none'}
        return JsonResponse(data)
    return HttpResponseNotAllowed('POST')


@login_required
def voted_list_view(request):
    if(request.user.info.is_cr):
        department = request.user.info.department
        year = request.user.info.join_year
        qs = UserInfo.objects.filter(department=department,join_year=year)
        context = {}
        upvote_percent = 0.0
        downvote_percent = 0.0
        novote_percent = 0.0
        for i in qs:
            try:
                upvote_percent = (abs(i.total_upvotes)/(abs(i.total_upvotes)+abs(i.total_downvotes)+abs(i.total_novotes)))*100
            except ZeroDivisionError:
                upvote_percent = 0.0
            try:
                downvote_percent = ((abs(i.total_downvotes))/(abs(i.total_upvotes)+abs(i.total_downvotes)+abs(i.total_novotes)))*100
            except ZeroDivisionError:
                downvote_percent = 0.0
            try:
                novote_percent = ((abs(i.total_novotes))/(abs(i.total_upvotes)+abs(i.total_downvotes)+abs(i.total_novotes)))*100
            except ZeroDivisionError:
                novote_percent = 0.0
            context[i.user.username] = (
                {'upvote':round(upvote_percent,2),
                'downvote':round(downvote_percent,2),
                'novote':round(novote_percent,2)
                }
            )
        return render(request,'reporter/voted-list.html',{'object_list':context})
    raise PermissionDenied


@login_required
def deadline_add_view(request):
    id_ = int(request.POST.get('id',None))
    form = DeadlineForm(request.POST)
    if(form.is_valid()):
        deadline = form.cleaned_data['deadline']
        live = datetime.datetime.now(pytz.timezone('Asia/Kolkata'))
        if((live.date()==deadline.date() and live.time()<deadline.time()) or(live.date()<deadline.date())):
            report_obj = get_object_or_404(Report,id=id_)
            if((report_obj.active == True and report_obj.resolved == False) or (request.user.info.is_cr)):
                if((request.user.info.is_cr and request.user.info.department == report_obj.department and request.user.info.join_year == report_obj.year)):
                    report_obj.deadline = deadline
                    report_obj.save()
        else:
            messages.error(request,'Deadline Must Be Higher than Current Time!')
    else:
        messages.error(request,'Invalid-Datetime')
    return redirect("reporter:index")


@login_required
def deadline_remove_view(request,pk):
    report_obj = get_object_or_404(Report,id=pk)
    if((report_obj.active == True and report_obj.resolved == False) or (request.user.info.is_cr)):
        if((request.user.info.is_cr and request.user.info.department == report_obj.department and request.user.info.join_year == report_obj.year)):
            report_obj.deadline = None
            report_obj.save()
    return redirect("reporter:index")


@login_required
def contactlist_list_view(request):
    user = request.user.info
    qs = ContactList.objects.filter(department=user.department,year=user.join_year,approved=True)
    return render(request,'reporter/contact-list.html',{'object_list':qs})


@login_required
def contactlist_add_view(request):
    form = ContactListForm()
    if(request.method=='POST'):
        form = ContactListForm(request.POST)
        if(form.is_valid()):
            user_obj = request.user.info

reporter/templates/reporter/archived.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

{% if request.user.is_authenticated %}
    <h4>Department: {{request.user.info.department|upper}} {{request.user.info.join_year}}</h4>
    <a href="{% url 'reporter:index' %}">Back to Active List</a>
    <hr>
    {% for issue in issue_list %}
    <div class="card border-primary mb-3" style="max-width: 45rem;">
        <div class="card-header">{{issue.user.user.first_name}} ({{issue.user.user.username}}) {% if issue.user.is_cr %}<strong>(CR)</strong>{% endif %} {% if request.user.info.is_cr %}<button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteModal">X</button> <a class="btn btn-warning ml-2" href="{% url 'reporter:close' issue.id %}">Open</a> {% endif %}</div>
        <div class="card-body text-primary">
          <h5 class="card-title">{{issue.content}}</h5>
          <p class="card-text">Resolved on: {{issue.updated}}</p>
        </div>
    </div>
    {% include 'reporter/modal_.html' with id=issue.id %}
    {% empty %}
    <p class="lead">No Issues in Archive!</p>
    {% endfor %}
{% endif %}

{% endblock %}

reporter/templates/reporter/closed.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

{% if request.user.is_authenticated %}
    <h4 class=mt-2>Department: {{request.user.info.department|upper}} {{request.user.info.join_year}}</h4>
    <a href="{% url 'reporter:index' %}"><i class="fa fa-arrow-left"></i> Active List</a>
    <hr>
    <p class="mt-2 lead text-center">Closed Issues</p>
    {% for issue in issue_list %}
    <div class="card border-primary mb-3" style="max-width: 45rem;">
        <div class="card-header">{{issue.user.user.first_name}} ({{issue.user.user.username}}) {% if issue.user.is_cr %}<strong>(CR)</strong>{% endif %} {% if request.user.info.is_cr %}<button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteModal">X</button> <a class="btn btn-warning ml-2" href="{% url 'reporter:close-issue' issue.id %}">Open</a> {% endif %} {% if issue.cr_line %}<a class="btn btn-success" href="{% url 'reporter:resolve-issue' issue.id %}">Resolve</a>{% endif %}</div>
        <div class="card-body text-primary">
          <h5 class="card-title">{{issue.title}}</h5>
          <p class="card-text" >{{issue.content|safe}}</p>
          <p class="card-text">Posted on: {{issue.timestamp|date:'d-m-Y H:i'}}</p>
          {% if not issue.anonymized %}
          <a class="btn btn-primary btn-sm my-2" href="{% url 'reporter:voted-users' issue.id %}">Voted Users</a>
          {% endif %}
          {% if issue.cr_line %}
          <p class="card-text resolve-message"><em>Resolved Message: </em><span style="color: black;">{{issue.cr_line}}</span></p>
          <a class="btn btn-dark" href="{% url 'reporter:resolve-line-delete' issue.id %}">Remove Message</a>
          {% else %}
          <form action="{% url 'reporter:close-stage' %}" method="post">
            {% csrf_token %}
            <div class="row">
              <div class="col-lg-5 col-md-7 col-sm-8">
                <input class="form-control" type="text" name="c-line">
              </div>
              <div class="col-2">
                  <input class="btn btn-primary btn-sm mt-1" type="submit" value="Add">
              </div>
            </div>
            <input type="hidden" name="id" value="{{issue.id}}">
          </form>
          {% endif %}
        </div>
        <div class="results ml-2">
          <p>Upvotes: {{issue.upvotes}}</p>
          <p>Downvotes: {{issue.downvotes}}</p>
        </div>
    </div>
    {% include 'reporter/modal_.html' with id=issue.id %}
    {% empty %}
    <p class="lead">No Issues Closed!</p>
    {% endfor %}
{% endif %}

{% endblock %}

reporter/templates/reporter/contact-add.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<h2 class="mt-2"><i class="fa fa-user-plus"></i> Add New Contact</h2>
<hr>
<div class="row">
    <div class="col-lg-7 col-md-10 col-sm-12">
        <form action="{% url 'reporter:contact-add' %}" method="post">
            {% csrf_token %}
            {{form|crispy}}
            <input class="btn btn-primary mb-2" type="submit" value="Add">
        </form>
    </div>
</div>

{% endblock %}

reporter/templates/reporter/contact-list.html
{% extends 'base.html' %}

{% block content %}
<h2><i class="fa fa-user-circle"></i> Contact List</h2>
<a href="{% url 'reporter:index' %}"><i class="fa fa-arrow-left"></i> Active List</a>
<a class="ml-4 rcolor" href="{% url 'reporter:contact-add' %}"><i class="fa fa-user-plus"></i> Add +</a>
{% if request.user.info.is_cr %}
<a class=" btn btn-primary btn-sm ml-2" href="{% url 'reporter:contact-pending' %}"><i class="fa fa-clock-o"></i> Pending List <span class="badge badge-dark">{{pending_contact_count}}</span></a>
{% endif %}
<hr>
<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
      </tr>
    </thead>
    <tbody>
      {% for object in object_list %}
      <tr>
        <th scope="row">{{forloop.counter}}</th>
        <td>{{object.name}} ({{object.course}})</td>
        <td>{% if object.email %}Email: {{object.email}}{% endif %}<br>{% if object.phone %}Phone: {{object.phone}}{% endif %}</td>
        {% if request.user.info == object.user or request.user.info.is_cr %}
        <td><a class="btn btn-danger btn-sm" href="{% url 'reporter:contact-delete' object.id %}"><i class="fa fa-trash-o"></i> Delete</a></td>
        {% endif %}
      </tr>
      {% empty %}
      <p class="lead">No List Available!</p>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

reporter/templates/reporter/contact-pending.html
{% extends 'base.html' %}

{% block content %}
<h2 class="mt-2">Pending List</h2>
<a href="{% url 'reporter:index' %}"><i class="fa fa-arrow-left"></i> Active List</a>
<hr>
<div class="table-responsive">
  <table class="table table-hover">
    <thead>
      <tr>
      </tr>
    </thead>
    <tbody>
      {% for object in object_list %}
      <tr>
        <th scope="row">{{forloop.counter}}</th>
        <td>{{object.name}} ({{object.course}})</td>
        <td>{% if object.email %}Email: {{object.email}}{% endif %}<br>{% if object.phone %}Phone: {{object.phone}}{% endif %}</td>
        <td><a class="btn btn-success" href="{% url 'reporter:contact-approve' object.id %}">Approve It</a></td>
        <td><a class="btn btn-danger" href="{% url 'reporter:contact-delete' object.id %}">Remove</a></td>
      </tr>
      {% empty %}
      <p class="lead">No List Available!</p>
      {% endfor %}
    </tbody>
  </table>
</div>
  {% endblock %}

reporter/templates/reporter/edit-issue.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

{% block head %} {{ form.media }} {% endblock %}

<h2 class="mt-2">Edit Issue</h2>
<div class="row">
    <div class="col-lg-7 col-md-10 col-sm-12">
        <form action="{% url 'reporter:edit' issue.id %}" method="post">
            {% csrf_token %}
            {{form|crispy}}
            <input class="btn btn-primary" type="submit" value="Save Edit">
        </form>
    </div>
</div>
    
{% endblock %}

reporter/templates/reporter/info-add.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<h2 class="mt-2">Add New Info</h2>
<hr>
<div class="row">
    <div class="col-lg-7 col-md-10 col-sm-12">
        <form action="{% url 'reporter:info-add' %}" method="post">
            {% csrf_token %}
            {{form|crispy}}
            <input class="btn btn-primary mb-2" type="submit" value="Add">
        </form>
    </div>
</div>

{% endblock %}

reporter/templates/reporter/issue-form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block head %} {{ form.media }} {% endblock %}

{% block content %}
<h2 class="mt-2"><i class="fa fa-pencil-square-o"></i> Add New Issue</h2>
<div>
    <div class="row">
        <div class="col-lg-7 col-md-10 col-sm-12">
            <form action="{% url 'reporter:issue-form' %}" method="post">
                {% csrf_token %}
                {{form|crispy}}
                <input class="btn btn-primary mb-2" type="submit" value="Save">
            </form>
        </div>
    </div>
</div>
    
{% endblock %}

reporter/templates/reporter/mail-modal_.html
 <!-- Modal -->
  <div class="modal fade" id="reminderModal" tabindex="-1" aria-labelledby="reminderModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Reminder</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          Remainder Mail will be Send to Entire Class!
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <a class="btn btn-primary" href="{% url 'reporter:mail' %}">Send Now!</a>
        </div>
      </div>
    </div>
  </div>

reporter/templates/reporter/resolved.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

{% if request.user.is_authenticated %}
    <h4 class="mt-2">Department: {{request.user.info.department|upper}} {{request.user.info.join_year}}</h4>
    <a href="{% url 'reporter:index' %}"><i class="fa fa-arrow-left"></i> Active List</a>
    <hr>
    <p class="mt-2 lead text-center">Resolved Issues</p>
    {% for issue in issue_list %}
    <div class="card border-primary mb-3" style="max-width: 45rem;">
        <div class="card-header">{{issue.user.user.first_name}} ({{issue.user.user.username}}) {% if issue.user.is_cr %}<strong>(CR)</strong>{% endif %} {% if request.user.info.is_cr %}<button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteModal">X</button>{% endif %}</div>
        <div class="card-body text-primary">
            <h5 class="card-title">{{issue.title}}</h5>
            <p class="card-text" >{{issue.content|safe}}</p>
            <p class="card-text">Resolved on: {{issue.updated|date:'d-m-Y H:i'}}</p>
            <p class="card-text resolve-message"><em>Resolved Message: </em><span style="color: black;">{{issue.cr_line}}</span></p>
            {% if not issue.anonymized %}
            <a class="btn btn-primary btn-sm my-2" href="{% url 'reporter:voted-users' issue.id %}">Voted Users</a>
            {% endif %}
        </div>
        <div class="results ml-2">
            <p>Upvotes: {{issue.upvotes}}</p>
            <p>Downvotes: {{issue.downvotes}}</p>
        </div>
    </div>
    {% include 'reporter/modal_.html' with id=issue.id %}
    {% empty %}
    <p class="lead">No Issues, Resolved yet!</p>
    {% endfor %}
{% endif %}

{% endblock %}