infolist/urls.py
from django.urls import path
from . import views

app_name = 'infolist'

urlpatterns=[
    path('',views.info_list_display_view,name='list'),
    path('add-subject/',views.info_list_add_subject_view,name='add-subject'),
    path('delete-subject/<int:id>/',views.info_list_delete_subject_view,name='delete-subject'),
    path('add/',views.info_list_add_view,name='add-info'),
    path('pending/',views.info_list_pending_list_view,name='pending'),
    path('approve/<int:id>/',views.info_list_approve_view,name='approve'),
    path('delete/<int:id>/',views.info_list_delete_view,name='delete'),
]

issue_reporter_src/urls.py
from django.contrib import admin
from django.urls import path,include
from infolist.views import meet_links_webpage

urlpatterns = [
    path('admin/', admin.site.urls),
    #External
    path('accounts/', include('allauth.urls')),
    path('tinymce/', include('tinymce.urls')),
    #Local
    path('',include('reporter.urls',namespace='reporter')),
    path('polling/',include('polling.urls',namespace='polling')),
    path('info-list/',include('infolist.urls',namespace='infolist')),
    path("msm19/",meet_links_webpage),
]

polling/urls.py
from django.urls import path
from . import views

app_name = 'polling'

urlpatterns=[
    path('',views.polling_list_view,name='list'),
    path('<int:id>/',views.polling_detail_view,name='detail'),
    path('submit/',views.poll_submit_view,name='submit'),
    path('close/<int:id>/',views.poll_close_view,name='close'),
    path('delete/<int:id>/',views.poll_delete_view,name='delete'),
    path('results/',views.poll_results_list,name='result-list'),
    path('result/<int:id>/',views.poll_result_detail,name='result-detail'),

    #API ENDPOINTS
    path('new/',views.poll_create_view,name='create'),
]

reporter/urls.py
from django.urls import path
from . import views

app_name = 'reporter'

urlpatterns=[
    path('',views.index_view,name='index'),
    path('about-us/',views.about_view,name='about'),
    path('feed-back/',views.feedback_view,name='feed-back'),
    path('documentation/',views.documentation_view,name='documentation'),
    path('send-mail/',views.send_remainder_mail_view,name='mail'),

    path('report/',views.issue_form_view,name='issue-form'),
    path('close-stage/<int:pk>/',views.close_issue_view,name='close-issue'),
    path('close-delete/<int:pk>/',views.delete_resolve_line_view,name='resolve-line-delete'),
    path('resolved/',views.resolved_view,name='resolved'),
    path('resolve-issue/<int:pk>',views.resolve_issue_view,name='resolve-issue'),
    path('close/',views.close_view,name='close-stage'),
    path('delete/<int:pk>/',views.delete_issue_view,name='delete'),
    path('edit/<int:pk>/',views.edit_issue_view,name='edit'),
    path('voted-list/',views.voted_list_view,name='voted-list'),
    path('deadline-add/',views.deadline_add_view,name='add-deadline'),
    path('deadline-remove/<int:pk>',views.deadline_remove_view,name='remove-deadline'),
    path('voted-list/<int:id>/',views.voted_users,name='voted-users'),
    
    path('contact-list/',views.contactlist_list_view,name='contact-list'),
    path('contact-pending/',views.contactlist_cr_pending_list,name='contact-pending'),
    path('contact-add/',views.contactlist_add_view,name='contact-add'),
    path('contact-approve/<int:pk>/',views.contactlist_approve_view,name='contact-approve'),
    path('contact-delete/<int:pk>/',views.contactlist_delete_view,name='contact-delete'),

    #Vote API EndPoints
    path('update-vote/',views.vote_update_view,name='vote-update'),
    path('get-vote/',views.vote_get_view,name='vote-get'),
]

infolist/models.py
from django.db import models
from profiles.models import UserInfo


class Subject(models.Model):
    subject = models.CharField(max_length=56)
    department = models.CharField(max_length=20,blank=True)
    year = models.CharField(max_length=4,blank=True)

    def __str__(self):
        return str(self.subject)


class InfoList(models.Model):
    user = models.ForeignKey(UserInfo,on_delete=models.CASCADE,blank=True)
    subject = models.ForeignKey(Subject,on_delete=models.CASCADE)
    title = models.CharField(max_length=128)
    content = models.TextField()
    department = models.CharField(max_length=20,blank=True)
    year = models.CharField(max_length=4,blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)

    def __str__(self):
        return str(self.title[:30])

    class Meta:
        ordering = ['-timestamp']

class MeetLinks(models.Model):
    subject_name = models.CharField(max_length=100,blank=True)
    subject_url = models.CharField(max_length=100,blank=True)

    def __str__(self):
        return str(self.subject_name+(self.subject_url))

infolist/forms.py
from django import forms

from tinymce.widgets import TinyMCE
from .models import Subject,InfoList

class InfoListForm(forms.ModelForm):
    def __init__(self,department,year,*args,**kwargs):
        super(InfoListForm,self).__init__(*args,**kwargs)
        self.fields['subject'].queryset = Subject.objects.filter(department=department,year=year)

    class Meta:
        model = InfoList
        fields = ['subject','title','content']
        widgets = {
            'content':TinyMCE(attrs={'cols': 80, 'rows': 15})
        }


class SubjectForm(forms.ModelForm):
    class Meta:
        model = Subject
        fields = ['subject']

infolist/views.py
from django.shortcuts import redirect, render,get_object_or_404
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.contrib import messages

from .models import InfoList,Subject, MeetLinks
from .forms import InfoListForm,SubjectForm

@login_required
def info_list_display_view(request):
    subjects = Subject.objects.filter(department=request.user.info.department,year=request.user.info.join_year)
    qs = InfoList.objects.filter(department=request.user.info.department,year=request.user.info.join_year,approved=True)
    data = []
    for i in subjects:
        objects = qs.filter(subject=i)
        if(objects.count()==0):
            continue
        data.append([objects,i])
    return render(request,'infolist/list.html',{'object_list':data})

@login_required
def info_list_add_subject_view(request):
    if(not request.user.info.is_cr):
        raise PermissionDenied
    form = SubjectForm()
    subjects = Subject.objects.filter(department=request.user.info.department,year=request.user.info.join_year)
    if request.method=='POST':
        form = SubjectForm(request.POST)
        if(form.is_valid()):
            subject = request.POST.get("subject")
            sub_obj,created = Subject.objects.get_or_create(department=request.user.info.department,year=request.user.info.join_year,subject=subject)
            if created:
                messages.success(request,"Subject Added!")
            else:
                messages.info(request,"Subject Already Exists!")
        else:
            messages.error(request,"Form is Invalid!")
        return redirect('infolist:add-subject')
    return render(request,'infolist/add-subject.html',{'form':form,'subjects':subjects})


@login_required
def info_list_delete_subject_view(request,id):
    object = get_object_or_404(Subject,pk=id)
    object.delete()
    messages.success(request,"Subject has Been Deleted!")
    return redirect("infolist:add-subject")


@login_required
def info_list_add_view(request):
    form = InfoListForm(request.user.info.department,request.user.info.join_year)
    if(request.method=='POST'):
        form = InfoListForm(request.user.info.department,request.user.info.join_year,request.POST)
        if(form.is_valid()):
            instance = form.save(commit=False)
            instance.user = request.user.info
            instance.department = request.user.info.department
            instance.year = request.user.info.join_year
            if(request.user.info.is_cr):
                instance.approved = True
                messages.info(request,"Info has been Added!")
            else:
                messages.info(request,"Info will be Added Once Approved by CR!")
            instance.save()
            return redirect('infolist:list')
    return render(request,'infolist/add-info.html',{'form':form})


@login_required
def info_list_pending_list_view(request):
    subjects = Subject.objects.filter(department=request.user.info.department,year=request.user.info.join_year)
    qs = InfoList.objects.filter(department=request.user.info.department,year=request.user.info.join_year,approved=False)
    data = []
    for i in subjects:
        objects = qs.filter(subject=i)
        if(objects.count()==0):
            continue
        data.append([objects,i])
    return render(request,'infolist/pending-list.html',{'object_list':data})


@login_required
def info_list_approve_view(request,id):
    if(not request.user.info.is_cr):
        raise PermissionDenied
    obj = get_object_or_404(InfoList,pk=id)
    obj.approved = True
    obj.save()
    messages.info(request,"Info has Been Approved!")
    return redirect("infolist:pending")


@login_required
def info_list_delete_view(request,id):
    obj = get_object_or_404(InfoList,pk=id)
    if(request.user.info==obj.user or request.user.info.is_cr):
        obj.delete()
        return redirect("infolist:list")    
    raise PermissionDenied



def meet_links_webpage(request):
    all_links = MeetLinks.objects.all()
    links = {"links": all_links}
    #User Permissions
    return render(request,"infolist/msm19.html", links)

infolist/templates/infolist/add-info.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block head %} {{ form.media }} {% endblock %}

{% block content %}
<h2 class="mt-2"><i class="fa fa-pencil-square-o"></i> Add Information</h2>
<a href="{% url 'infolist:list' %}"><i class="fa fa-arrow-left"></i> Info List</a>
<hr>
<div>
    <div class="row">
        <div class="col-lg-7 col-md-10 col-sm-12">
            <form action="{% url 'infolist:add-info' %}" method="post">
                {% csrf_token %}
                {{form|crispy}}
                <input class="btn btn-primary mb-2" type="submit" value="Add">
            </form>
        </div>
    </div>
</div>
    
{% endblock %}

infolist/templates/infolist/add-subject.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<h2 class="mt-2">Add New Subject</h2>
<a href="{% url 'infolist:list' %}"><i class="fa fa-arrow-left"></i> Info List</a>
<hr>
<div class="row">
    <div class="col-lg-6 col-md-8 col-sm-12">
        <form action="{% url 'infolist:add-subject' %}" method="post">
            {% csrf_token %}
            {{form|crispy}}
            <input class="btn btn-primary" type="submit" value="Add">
        </form>
    </div>
</div>
<div class="row">
    <div class="col-lg-6 col-md-8 col-sm-12">
        <p class="lead mt-2">Added Subjects</p>
        {% for object in subjects %}
        <div>
            <p><span>{{forloop.counter}}.</span> {{object.subject}}<a class="btn btn-danger btn-sm ml-2" href="{% url 'infolist:delete-subject' object.id %}"><i class="fa fa-trash-o"></i> Remove</a></p>
        </div>
        {% empty %}
            <p>No Subjects Added yet!</p>
        {% endfor %}
    </div>
</div>

{% endblock %}

infolist/templates/infolist/list.html
{% extends 'base.html' %}

{% block content %}
<h2 class="mt-3 text-center">TeamEzI Resolved</h2>
<h4 class="inline-block">Department: {{request.user.info.department|upper}} {{request.user.info.join_year}}</h4>
<a class="btn btn-secondary ml-3 mt-2" href="{% url 'polling:list' %}"><i class="fa fa-bar-chart"></i> Live Polls <span class="badge badge-light">{{live_polls_count}}</span></a>
<a class="btn btn-secondary ml-3 mt-2" href="{% url 'reporter:index' %}"><i class="fa fa-exclamation-circle"></i> Issues</a>
<h3 class="mt-2">Welcome, {{request.user.first_name}} {{request.user.last_name}}</h3>

<a class="btn btn-primary btn-sm" href="{% url 'infolist:add-info' %}"><i class="fa fa-plus-circle"></i> Add New</a>
{% if request.user.info.is_cr %}
<a class="btn btn-primary btn-sm" href="{% url 'infolist:add-subject' %}"><i class="fa fa-calendar-plus-o"></i> Add New Subject</a>
<a class="btn btn-success btn-sm" href="{% url 'infolist:pending' %}"> <i class="fa fa-history"></i> Pending <span class="badge badge-danger">{{pending_info_list}}</span></a>
{% endif %}
<hr>
<h2 class="mt-2 text-center">Information List</h2>
{% for objects,subject in object_list %}
    <p class="lead">{{subject.subject}}</p>
    {% for object in objects %}
    <div class="row">
        <div class="col-lg-6 col-md-8 col-sm-12">
            <div class="card my-2">
                <div class="card-body">
                <h5 class="card-title">{{object.title}}</h5>
                <h6 class="card-subtitle mb-2 text-muted">{{subject.subject}}</h6>
                <p class="card-text">{{object.content|safe}}</p>
                {% if request.user.info.is_cr or request.user.info == object.user %}
                <a href="{% url 'infolist:delete' object.id %}" class="card-link btn btn-danger btn-sm"><i class="fa fa-trash-o"></i> Delete</a>
                {% endif %}
                </div>
            </div>
        </div>
    </div>
        {% empty %}
        <p>No Data for {{subject.subject}}!</p>
        {% endfor %}
    {% endfor %}
{% endblock %}

infolist/templates/infolist/msm19.html
{% extends "base.html" %}

{%block content%}

<h2 class="mt-3">Meet Links</h2>

{% for link in links %}
<ul>
    <li class="mt-3"><a class="text-dark"target="_blank" href={{link.subject_url}}><u>{{link.subject_name}}</u></a></li>
</ul>
{% endfor %}

{%endblock%}

infolist/templates/infolist/pending-list.html
{% extends 'base.html' %}

{% block content %}
<h2 class="mt-2 text-center">Pending Information List</h2>
<a href="{% url 'infolist:list' %}"><i class="fa fa-arrow-left"></i> Info List</a>
<hr>
{% for objects,subject in object_list %}
    <p class="lead">{{subject.subject}}</p>
    {% for object in objects %}
    <div class="row">
        <div class="col-lg-6 col-md-8 col-sm-12">
            <div class="card">
                <div class="card-body">
                <h5 class="card-title">{{object.title}}</h5>
                <h6 class="card-subtitle mb-2 text-muted">{{subject.subject}}</h6>
                <p class="card-text">{{object.content|safe}}</p>
                <a href="{% url 'infolist:approve' object.id %}" class="card-link btn btn-success btn-sm"><i class="fa fa-check-circle"></i> Approve</a>
                <a href="{% url 'infolist:delete' object.id %}" class="card-link btn btn-danger btn-sm"><i class="fa fa-trash-o"></i> Delete</a>
                </div>
            </div>
        </div>
    </div>
        {% empty %}
        <p>No Data for {{subject.subject}}!</p>
        {% endfor %}
    {% empty %}
    <p>No Information Pending Yet!</p>
    {% endfor %}

{% endblock %}