issue_reporter_src/urls.py
from django.contrib import admin
from django.urls import path,include
from infolist.views import meet_links_webpage

urlpatterns = [
    path('admin/', admin.site.urls),
    #External
    path('accounts/', include('allauth.urls')),
    path('tinymce/', include('tinymce.urls')),
    #Local
    path('',include('reporter.urls',namespace='reporter')),
    path('polling/',include('polling.urls',namespace='polling')),
    path('info-list/',include('infolist.urls',namespace='infolist')),
    path("msm19/",meet_links_webpage),
]

polling/urls.py
from django.urls import path
from . import views

app_name = 'polling'

urlpatterns=[
    path('',views.polling_list_view,name='list'),
    path('<int:id>/',views.polling_detail_view,name='detail'),
    path('submit/',views.poll_submit_view,name='submit'),
    path('close/<int:id>/',views.poll_close_view,name='close'),
    path('delete/<int:id>/',views.poll_delete_view,name='delete'),
    path('results/',views.poll_results_list,name='result-list'),
    path('result/<int:id>/',views.poll_result_detail,name='result-detail'),

    #API ENDPOINTS
    path('new/',views.poll_create_view,name='create'),
]

reporter/urls.py
from django.urls import path
from . import views

app_name = 'reporter'

urlpatterns=[
    path('',views.index_view,name='index'),
    path('about-us/',views.about_view,name='about'),
    path('feed-back/',views.feedback_view,name='feed-back'),
    path('documentation/',views.documentation_view,name='documentation'),
    path('send-mail/',views.send_remainder_mail_view,name='mail'),

    path('report/',views.issue_form_view,name='issue-form'),
    path('close-stage/<int:pk>/',views.close_issue_view,name='close-issue'),
    path('close-delete/<int:pk>/',views.delete_resolve_line_view,name='resolve-line-delete'),
    path('resolved/',views.resolved_view,name='resolved'),
    path('resolve-issue/<int:pk>',views.resolve_issue_view,name='resolve-issue'),
    path('close/',views.close_view,name='close-stage'),
    path('delete/<int:pk>/',views.delete_issue_view,name='delete'),
    path('edit/<int:pk>/',views.edit_issue_view,name='edit'),
    path('voted-list/',views.voted_list_view,name='voted-list'),
    path('deadline-add/',views.deadline_add_view,name='add-deadline'),
    path('deadline-remove/<int:pk>',views.deadline_remove_view,name='remove-deadline'),
    path('voted-list/<int:id>/',views.voted_users,name='voted-users'),
    
    path('contact-list/',views.contactlist_list_view,name='contact-list'),
    path('contact-pending/',views.contactlist_cr_pending_list,name='contact-pending'),
    path('contact-add/',views.contactlist_add_view,name='contact-add'),
    path('contact-approve/<int:pk>/',views.contactlist_approve_view,name='contact-approve'),
    path('contact-delete/<int:pk>/',views.contactlist_delete_view,name='contact-delete'),

    #Vote API EndPoints
    path('update-vote/',views.vote_update_view,name='vote-update'),
    path('get-vote/',views.vote_get_view,name='vote-get'),
]

templates/about.html
{% extends 'base.html' %}

{% block content %}

<h1>About Us</h1>
<p>This project has been made to solve some of the various issues faced by the class and its representatives on a various basis</p>

<h2>Developed, Designed and Tested By:</h2>
<ul>
    <li><a class="green-link" target="none" href="https://github.com/ayushxeon">ayushxeon</a></li>
    <li><a class="green-link" target="none" href="https://github.com/TheOxFromOutOfTheBox">TheOxFromOutOfTheBox</a></li>
    <li><a class="green-link" target="none" href="https://github.com/Mohit-2007">Mohit-2007</a></li>
    <li><a class="green-link" target="none" href="https://github.com/anonshubh">anonshubh</a></li>
</ul>
<p>Contact Us: teameziportal@gmail.com</p>
<h2>Contributors</h2>
<p>We encourage people to have a look at our repo on <a target="none" class="rcolor" href="https://github.com/anonshubh/issue-reporter">Github</a>, and provide us with feedback,suggestions and inputs. They are all very much apppreciated!!</p>
<ul>
    <li>Logo Designed by <a class="green-link" target="none" href="https://www.instagram.com/vismay_chand/">Vismaychand</a></li>
</ul>


{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
     <!-- Bootstrap CSS -->
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
     
    <!-- FAVICON -->
    <link rel ="apple-touch-icon" sizes ="180x180" href ="{% static 'images/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes ="16x16" href ="{% static 'images/fav/favicon-16x16.png' %}">
    <link rel="manifest" href ="{% static 'images/fav/site.webmanifest' %}">

     <!-- Custom CSS -->
     <link rel="stylesheet" href="{% static 'css/style.css' %}">

     <!-- Google Fonts -->
     <!-- <link href="https://fonts.googleapis.com/css2?family=Courier+Prime&display=swap" rel="stylesheet"> -->
     <link href="https://fonts.googleapis.com/css2?family=Ubuntu&display=swap" rel="stylesheet"> 
    <!-- cdn link from font-awesome -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <title>{% block title %}Let's Resolve{% endblock %}</title>
    {% block head %} {% endblock %}
  </head>
  <body>

      <nav style="background-color:rgba(63, 61, 61, 0.89) ;" class="navbar navbar-expand-lg navbar-dark sticky-top">
        <a class="navbar-brand" href="{% url 'reporter:index' %}"><i class="fa fa-home"></i> Resolver</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link my-1 mr-2 text-center" href="{% url 'reporter:documentation' %}"><i class="fa fa-question-circle-o"></i> Need Help?</a>
            </li>
            <li class="nav-item">
              <a class="nav-link my-1 mr-2 text-center" href="{% url 'reporter:about' %}"><i class="fa fa-users"></i> About Us<span class="sr-only">(current)</span></a>
            </li>
            {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link btn btn-success" href="{% url 'account_logout' %}"><i class="fa fa-power-off"></i> Log Out</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link btn btn-success btn-sm ml-2 my-1 mr-2" href="{% url 'account_login' %}">Log In</a>
            </li>
            <li class="nav-item">
              <a class="nav-link btn btn-success btn-sm ml-2 my-1 mr-2" href="{% url 'account_signup' %}">Sign Up</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </nav>

    <div class="container">
      {% include 'messages_.html' %}
      {% block content %} {% endblock %}
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

    <!-- Custom Js -->
    <script src="{% static 'js/master.js' %}"></script>
    
    <!-- Page-Wise JS -->
    {% block script %} {% endblock %}

    <!-- Google Analytics -->
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-178498254-1"></script>
      <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());
        gtag('config', 'UA-178498254-1');
      </script>
  </body>
</html>

templates/documentation.html
{% extends 'base.html' %}

{% block title %}Documentation{% endblock %}

{% block content %}
    <h1 class="text-center mt-2"">TeamEzi! Documented</h1>
    <p>Hi! Welcome to TeamEzi! If there is something you don't understand,this is the place to come to!After you log in to the site,you see many buttons.You wonder,what does this button do?This is where it gets answered.</p>
    <ul>
        <li>
            <div class="text-center">
                <a class="btn btn-primary btn-sm mb-2">Add New Issue</a>
            </div>
            <p>Facing any issue in the class?Just post about your problem and what your desired solution is and then your classmates can express their agreement and disagreement using the upvote and downvote buttons. </p><br><br>
        </li>
        <li>
            <div class="text-center">
                <a class="btn btn-secondary btn-sm mb-2">Voting Data</a>
            </div>
            <p><b>FOR CR ONLY:<br></b>After closing of the issue(when deadline is completed),the CR can see the statistics of the vote.He can see:</p>
            <ol>
                <li>
                    Number of people who voted <b>FOR</b> the proposal.
                </li>
                <li>
                    Number of people who voted <b>AGAINST</b> the proposal.
                </li>
                <li>
                    Number of people who <b>SKIPPED</b> the vote.
                </li><br><br>
            </ol>
            <li>
                <div class="text-center">
                    <a class="btn btn-primary btn-sm mb-2">Contact List</a>
                    <a class="btn btn-primary btn-sm mb-2">Pending List</a>
                </div>
                <p>
                    Does anybody need the number or email id of a TA or Professor?This is where you will find it.Now you may wonder,how can you add to this list?When you go into the list,you will find a link at the top asking to add new contacts.On clicking that,you will be redirected to a form.On the submission of the form,your submission will be put on the Pending list,which will be then approved by the CR's before being added.
                </p>
            </li>
        <li>
            <div class="text-center">
                <a class="btn btn-warning btn-sm mb-2">Closed</a>
                <a class="btn btn-success btn-sm mb-2">Resolved</a>
            </div>
            <p>
                After you have posted your issue,your CR may have put a deadline on voting.After the deadline is passed,the issue is <b>OFFICIALLY</b> closed.You can no longer vote on it.Now,it's in the hands of your CR.Once they finish working on the solution,it will be moved into the <b>RESOLVED</b> category.
            </p>
        </li>
        <li>
            <div class="text-center">
                <a class="btn btn-secondary btn-sm mb-2">Live Polls</a>
                <a class="btn btn-primary btn-sm mb-2">Create a Poll</a>
                <a class="btn btn-success btn-sm mb-2">Results</a>
            </div>
            <p>
                Suppose you have a test coming up,but the Professor has asked you to pick the date?You have many options!!Which one to choose?This is where the poll feature comes in.You add a new poll,with a number of options,and then wait for others to vote.Before the closure of the poll,nobody can know the current status,even the CR!After that,the results will be on display using the Results Button.
            </p>
        </li>
    </ul>
{% endblock %}

templates/messages_.html
{% for message in messages %}
  <div class="alert {{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div>
{% endfor %}